
<feed xmlns="http://www.w3.org/2005/Atom">
    <title>CCN Featured RSS Feed</title>
    <link href="{{ url('/') }}/"/>
    <updated>{{ Carbon\Carbon::now()->format("Y-m-d\TH:i:sP") }}</updated>
    <id>{{ url('/') }}/</id>
    @foreach ($events as $event)
        <entry>
            <title>{{ $event->summary }}</title>
            {{-- AUTHORS. Generated by Author Email --}}
            @if($event->creator->email == 'rina@rinajensen.com')
                <author>
                    <name>{{ 'Rina Jensen' }}</name>
                </author>
            @elseif($event->creator->email == 'mstonekinghome@gmail.com')
                <author>
                    <name>{{ 'Matthew Stoneking' }}</name>
                </author>
            @elseif($event->creator->email == 'artistro08@gmail.com')
                <author>
                    <name>{{ 'Devin Green' }}</name>
                </author>
            @elseif($event->creator->email == 'wesley.adams.davis@gmail.com')
                <author>
                    <name>{{ 'Wesley Davis' }}</name>
                </author>
            @endif
            <id>{{ $event->htmlLink }}</id>
            <published>{{ date("Y-m-d\TH:i:sP", strtotime($event->created)) }}</published>
            <updated>{{ date("Y-m-d\TH:i:sP", strtotime($event->created)) }}</updated>
            <summary>{{ $event->startDateTime->format('g:i A') }} - {{ $event->endDateTime->format('g:i A') }}</summary>
            <content type="html">{{ htmlspecialchars($event->description, ENT_XML1, 'UTF-8') }}</content>
        </entry>
    @endforeach
</feed>

